create table if not exists public.custom_word_readings (
  id bigint generated by default as identity primary key,
  word_key text not null unique,
  word text not null,
  reading_katakana text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_custom_word_readings_updated_at on public.custom_word_readings;
create trigger trg_custom_word_readings_updated_at
before update on public.custom_word_readings
for each row
execute function public.set_updated_at();

alter table public.custom_word_readings enable row level security;

drop policy if exists custom_word_readings_read_all on public.custom_word_readings;
create policy custom_word_readings_read_all
on public.custom_word_readings
for select
to anon, authenticated
using (true);
